USE customers;
SELECT *
FROM my_table 
LIMIT 10;

-- Q1: What is total revenue generated by male vs female customers
SELECT gender, SUM(purchase_amount) as revenue
FROM my_table
GROUP BY gender;

-- Q2: Which customer use discount but still spend more than the average purchase amount

SELECT customer_id, AVG(purchase_amount) as average_purchase_amount
FROM my_table
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM my_table)
GROUP BY customer_id;

-- Q3: Which has the top 5 product with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating),2) as avg_review_rating
FROM my_table
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4:Compare the average product amount between standard and express shipping
SELECT shipping_type, AVG(purchase_amount) as avg_product_amount
FROM my_table
WHERE shipping_type in ('Express','Standard')
GROUP BY shipping_type;

-- Q5:Do subscribe customer spend more? Comapre avg spend and total revenue between subscribed or not-subscribed
select subscription_status, avg(purchase_amount) as avg_spend, sum(purchase_amount) as total_revenue
from my_table
group by subscription_status;

-- Q6: Which 5 product have the highest percentage of purchases with discount applied
select item_purchased,
(100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*)) as discount_rate
from my_table
group by item_purchased
order by discount_rate desc;

-- Q7: Segment into new, returning and loyal based on their total number of previous purchases, and sow the count of each purchases
with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'new'
    when previous_purchases = 2 and 10 then 'returning'
    else 'loyal'
    end as customr_segment
from my_table
)
select customr_segment, count(*) as total_customer
from customer_type
group by customr_segment;

-- Q8: What are the top 3 most purchased product
with item_count as(
select category, item_purchased,
count(customer_id) as total_order,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from my_table
group by category, item_purchased

)
select category, item_purchased, item_rank, total_order
from item_count
where item_rank <= 3;

-- Q9:Are customers who are repeate buyers(more than 5 previous purchases) also likely to subscribed
select subscription_status, count(customer_id) as repeate_cus
from my_table
where previous_purchases >= 5
group by subscription_status; 

-- Q10: What was the revenue contribution of each age group
select age_group, sum(purchase_amount) as revenue_contributed
from my_table
group by age_group
order by revenue_contributed desc;